M48
; DRILL file KiCad 10.0.0 date 2026-05-01T20:27:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-01T20:27:17+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X166.446Y-75.6
X166.446Y-98.6
X187.45Y-75.6
X187.45Y-98.6
M30
