M48
; DRILL file KiCad 10.0.0 date 2026-06-04T17:36:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-04T17:36:21+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.130
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X77.763Y-45.1
T2
X64.723Y-108.438
X93.0Y-47.47
X154.06Y-120.56
X154.163Y-57.0
M30
